const languages = [
  {
    no: "0",
    name: "Afrikaans",
    native: "Afrikaans",
    code: "af",
  },
  {
    no: "1",
    name: "Albanian",
    native: "Shqip",
    code: "sq",
  },
  {
    no: "2",
    name: "Amharic",
    native: "አማርኛ",
    code: "am",
  },
  {
    no: "3",
    name: "Arabic",
    native: "العربية",
    code: "ar",
  },
  {
    no: "4",
    name: "Armenian",
    native: "Հայերեն",
    code: "hy",
  },
  {
    no: "5",
    name: "Assamese",
    native: "অসমীয়া",
    code: "as",
  },
  {
    no: "6",
    name: "Azerbaijani",
    native: "Azərbaycan dili",
    code: "az",
  },
  {
    no: "7",
    name: "Bashkir",
    native: "Башҡорт теле",
    code: "ba",
  },
  {
    no: "8",
    name: "Basque",
    native: "Euskara",
    code: "eu",
  },
  {
    no: "9",
    name: "Belarusian",
    native: "Беларуская",
    code: "be",
  },
  {
    no: "10",
    name: "Bengali",
    native: "বাংলা",
    code: "bn",
  },
  {
    no: "11",
    name: "Bosnian",
    native: "Bosanski",
    code: "bs",
  },
  {
    no: "12",
    name: "Bulgarian",
    native: "Български",
    code: "bg",
  },
  {
    no: "13",
    name: "Catalan",
    native: "Català",
    code: "ca",
  },
  {
    no: "14",
    name: "Cebuano",
    native: "Sinugbuanon",
    code: "ceb",
  },
  {
    no: "15",
    name: "Chinese (Simplified)",
    native: "中文简体",
    code: "zh-CN",
  },
  {
    no: "16",
    name: "Chinese (Traditional)",
    native: "中文繁體",
    code: "zh-TW",
  },
  {
    no: "17",
    name: "Chuvash",
    native: "Чăваш",
    code: "cv",
  },
  {
    no: "18",
    name: "Croatian",
    native: "Hrvatski",
    code: "hr",
  },
  {
    no: "19",
    name: "Czech",
    native: "Český",
    code: "cs",
  },
  {
    no: "20",
    name: "Danish",
    native: "Dansk",
    code: "da",
  },
  {
    no: "21",
    name: "Dari",
    native: "دری",
    code: "fa-AF",
  },
  {
    no: "22",
    name: "Dutch",
    native: "Nederlands",
    code: "nl",
  },

    {
      no: "23",
      name: "English",
      native: "English",
      code: "en",
      
    },
    {
      no: "24",
      name: "Estonian",
      native: "Eesti keel",
      code: "et",
    },
    {
      no: "25",
      name: "Filipino",
      native: "Filipino",
      code: "tl",
    },
    {
      no: "26",
      name: "Finnish",
      native: "Suomi",
      code: "fi",
    },
    {
      no: "27",
      name: "French",
      native: "Français",
      code: "fr",
    },
    {
      no: "28",
      name: "Galician",
      native: "Galego",
      code: "gl",
    },
    {
      no: "29",
      name: "Georgian",
      native: "ქართული",
      code: "ka",
    },
    {
      no: "30",
      name: "German",
      native: "Deutsch",
      code: "de",
    },
    {
      no: "31",
      name: "Greek",
      native: "Ελληνικά",
      code: "el",
    },
    {
      no: "32",
      name: "Gujarati",
      native: "ગુજરાતી",
      code: "gu",
    },
    {
      no: "33",
      name: "Haitian Creole",
      native: "Kreyòl ayisyen",
      code: "ht",
    },
    {
      no: "34",
      name: "Hausa",
      native: "Hausa",
      code: "ha",
    },
    {
      no: "35",
      name: "Hebrew",
      native: "עברית",
      code: "iw",
    },
    {
      no: "36",
      name: "Hindi",
      native: "हिन्दी",
      code: "hi",
    },
    {
      no: "37",
      name: "Hungarian",
      native: "Magyar",
      code: "hu",
    },
    {
      no: "38",
      name: "Icelandic",
      native: "Íslenska",
      code: "is",
    },
    {
      no: "39",
      name: "Indonesian",
      native: "Bahasa Indonesia",
      code: "id",
    },
    {
      no: "40",
      name: "Irish",
      native: "Gaeilge",
      code: "ga",
    },
    {
      no: "41",
      name: "Italian",
      native: "Italiano",
      code: "it",
    },
    {
      no: "42",
      name: "Japanese",
      native: "日本語",
      code: "ja",
    },
    {
      no: "43",
      name: "Kannada",
      native: "ಕನ್ನಡ",
      code: "kn",
    },
    {
      no: "44",
      name: "Kazakh",
      native: "Қазақ",
      code: "kk",
    },
    {
      no: "45",
      name: "Khmer",
      native: "ភាសាខ្មែរ",
      code: "km",
    },
    {
      no: "46",
      name: "Korean",
      native: "한국어",
      code: "ko",
    },
    {
      no: "47",
      name: "Kurdish",
      native: "کوردی",
      code: "ku",
    },
    {
      no: "48",
      name: "Kyrgyz",
      native: "Кыргызча",
      code: "ky",
    },
    {
      no: "49",
      name: "Lao",
      native: "ລາວ",
      code: "lo",
    },
    {
      no: "50",
      name: "Latvian",
      native: "Latviešu",
      code: "lv",
    },
    {
      no: "51",
      name: "Lithuanian",
      native: "Lietuvių kalba",
      code: "lt",
    },
    {
      no: "52",
      name: "Macedonian",
      native: "Македонски",
      code: "mk",
    },
    {
      no: "53",
      name: "Malay",
      native: "Bahasa Malaysia",
      code: "ms",
    },
    {
      no: "54",
      name: "Malayalam",
      native: "മലയാളം",
      code: "ml",
    },
    {
      no: "55",
      name: "Maltese",
      native: "Malti",
      code: "mt",
    },
    {
      no: "56",
      name: "Mongolian",
      native: "Монгол",
      code: "mn",
    },
    {
      no: "57",
      name: "Nepali",
      native: "नेपाली",
      code: "ne",
    },
    {
      no: "58",
      name: "Norwegian",
      native: "Norsk",
      code: "no",
    },
    {
      no: "59",
      name: "Pashto",
      native: "پښتو",
      code: "ps",
    },
    {
      no: "60",
      name: "Persian",
      native: "فارسی",
      code: "fa",
    },
    {
      no: "61",
      name: "Polish",
      native: "Polski",
      code: "pl",
    },
    {
      no: "62",
      name: "Portuguese",
      native: "Português",
      code: "pt",
    },
    {
      no: "63",
      name: "Romanian",
      native: "Română",
      code: "ro",
    },
    {
      no: "64",
      name: "Russian",
      native: "Русский",
      code: "ru",
    },
    {
      no: "65",
      name: "Sinhala",
      native: "සිංහල",
      code: "si",
    },
    {
      no: "66",
      name: "Slovak",
      native: "Slovenčina",
      code: "sk",
    },
    {
      no: "67",
      name: "Slovenian",
      native: "Slovensko",
      code: "sl",
    },
    {
      no: "68",
      name: "Spanish",
      native: "Español",
      code: "es",
    },
    {
      no: "69",
      name: "Swahili",
      native: "Kiswahili",
      code: "sw",
    },
    {
      no: "70",
      name: "Swedish",
      native: "Svenska",
      code: "sv",
    },
    {
      no: "71",
      name: "Tajik",
      native: "Тоҷикӣ",
      code: "tg",
    },
    {
      no: "72",
      name: "Tamil",
      native: "தமிழ்",
      code: "ta",
      
    },
    {
      no: "73",
      name: "Telugu",
      native: "తెలుగు",
      code: "te",
    },
    {
      no: "74",
      name: "Thai",
      native: "ไทย",
      code: "th",
    },
    {
      no: "75",
      name: "Turkish",
      native: "Türkçe",
      code: "tr",
    },
    {
      no: "76",
      name: "Ukrainian",
      native: "Українська",
      code: "uk",
    },
    {
      no: "77",
      name: "Urdu",
      native: "اردو",
      code: "ur",
    },
    {
      no: "78",
      name: "Uzbek",
      native: "O'zbekcha",
      code: "uz",
    },
    {
      no: "79",
      name: "Vietnamese",
      native: "Tiếng Việt",
      code: "vi",
    },
    {
      no: "80",
      name: "Welsh",
      native: "Cymraeg",
      code: "cy",
    },
    {
      no: "81",
      name: "Western Frisian",
      native: "Frysk",
      code: "fy",
    },
    {
      no: "82",
      name: "Xhosa",
      native: "isiXhosa",
      code: "xh",
    },
    {
      no: "83",
      name: "Yiddish",
      native: "ייִדיש",
      code: "yi",
    },
    {
      no: "84",
      name: "Zulu",
      native: "isiZulu",
      code: "zu",
    },
    
  ];

    
    
  